# Generated by Django 2.1.5 on 2019-01-30 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spike_stats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='winner',
            field=models.CharField(default='no winner', max_length=10),
        ),
    ]
