# Generated by Django 2.1.5 on 2019-04-05 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spike_stats', '0003_auto_20190209_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='game',
            name='winner',
            field=models.CharField(default='', max_length=20),
        ),
    ]
